name: CI

# on: [create, delete]
on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run ci.sh
      run: ci/ci_ubuntu_latest.sh
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: vst_ubuntu_latest
        path: vst_ubuntu_latest
